"""
auto_update_pcsp.py
===================

This script automates the process of updating the #define block in baseball_template.pcsp
with real probabilities generated by data_parser.py for any pitcher/batter matchup.

Usage:
    python auto_update_pcsp.py "Pitcher Name" "Batter Name"

Example:
    python auto_update_pcsp.py "Gerrit Cole" "Aaron Judge"

This will create a new file matchup.pcsp with the updated #define block.
"""

import sys
import re
from data_parser import get_matchup, generate_pcsp_defines

if len(sys.argv) != 3:
    print("Usage: python auto_update_pcsp.py \"Pitcher Name\" \"Batter Name\"")
    sys.exit(1)

pitcher = sys.argv[1]
batter = sys.argv[2]

# 1. Get the matchup parameters
define_block = generate_pcsp_defines(get_matchup(pitcher, batter))

template_path = "baseball_template.pcsp"
output_path = "matchup.pcsp"

# 2. Read the template file
with open(template_path, "r") as f:
    content = f.read()

# 3. Replace the old #define block with the new one
pattern = r"((?:\s*//.*\n)?(?:\s*#define[^\n]*\n)+)"
new_content = re.sub(pattern, define_block + "\n", content, count=1, flags=re.MULTILINE)

# 4. Save the updated file (as matchup.pcsp)
with open(output_path, "w") as f:
    f.write(new_content)

print(f"Updated {output_path} with real probabilities for {pitcher} vs {batter}!")
