"""
auto_update_pcsp.py
===================

This script automates the process of updating the #define block in
baseball_template.pcsp with real probabilities generated by data_parser.py
for any pitcher/batter matchup.

Usage:
    python auto_update_pcsp.py "Pitcher Name" "Batter Name"

Example:
    python auto_update_pcsp.py "Gerrit Cole" "Aaron Judge"

This will create a new file matchup.pcsp with the updated #define block.
"""

import sys
import re
from data_parser import get_matchup, generate_pcsp_defines

if len(sys.argv) != 3:
    print("Usage: python auto_update_pcsp.py \"Pitcher Name\" \"Batter Name\"")
    sys.exit(1)

pitcher = sys.argv[1]
batter = sys.argv[2]

# 1. Get the matchup parameters
define_block = generate_pcsp_defines(get_matchup(pitcher, batter))

template_path = "baseball_template.pcsp"
output_path = "matchup.pcsp"

# 2. Read the template file
with open(template_path, "r") as f:
    content = f.read()

# 3. Replace the full header define block.
# This includes everything from the top comments/defines up to the first var.
pattern = r"\A(?:\s*//.*\n|\s*#define[^\n]*\n|\s*\n)*?(?=\s*var\s+)"
new_content = re.sub(
    pattern,
    define_block + "\n",
    content,
    count=1,
    flags=re.MULTILINE
)


# 4. Remove all comments (// ...) from the new content before saving.
# Also ensure file starts at line 1 (no leading blank lines).
no_comments_content = re.sub(r"//.*", "", new_content)
# Remove leading whitespace and blank lines
no_comments_content = no_comments_content.lstrip()
with open(output_path, "w") as f:
    f.write(no_comments_content)

print(
    f"Updated {output_path} with real probabilities for "
    f"{pitcher} vs {batter}!"
)
